@host = http://localhost:5001

### Get current minimum log level
GET {{host}}/logging/get-min-level

### Update minimum log level to Debug
POST {{host}}/logging/update-min-level
Content-Type: application/json

{
  "minimumLogLevel": "Information"
}

### Update minimum log level to Information
POST {{host}}/logging/update-min-level
Content-Type: application/json

{
  "minimumLogLevel": "Warning"
}

### Update minimum log level to Warning
POST {{host}}/logging/update-min-level
Content-Type: application/json

{
  "minimumLogLevel": "Error"
}

### Log to all levels
POST {{host}}/logging/log-to-all-levels